title: "HTML-CSS"
description: "Curso do curso em video"
author: "João Ricardo"
baseurl: ""
url: "https://joaoric30a.github.io/html-css"
theme: jekyll-theme-minimal
markdown: kramdown
permalink: pretty
socials:
  github: "https://github.com/joaoric30a"

# Configurações extras de exibição
collections:
  posts:
    output: true
